project:
  type: website

website:
  title: "ISSS608-VAA"
  google-analytics: "G-8R61GXQYCW"
  navbar:
    left:
    - text: "Hands On Exercises"
      menu: 
        - text: "Hands On Exercise 1"
          href: "HandsOn_Exercises/HandsOn_Ex01/HandsOnEx01.html"
        - text: "Hands On Exercise 2"
          href: "HandsOn_Exercises/HandsOn_Ex02/HandsOnEx02.html"
    
    tools:
      - icon: github
        href: "https://github.com/sndrjcb/ISSS608-VAA"
      - icon: linkedin
        href: "https://www.linkedin.com/in/sandrajacob99/"
      - icon: telegram
        href: "https://t.me/sndrjcb"

format:
  html:
    theme: lux
    light: flatly
    dark: darkly
    highlight-style: monokai
    title-block-banner: '#300713'
    title-block-banner-color: white
    css: styles.css
    toc: true

editor: visual

