project:
  type: website

website:
  title: "ISSS608-VAA"
  google-analytics: "G-8R61GXQYCW"
  navbar:
    left:
    - text: "Hands On Exercises"
      menu: 
        - text: "Hands On Exercise 1"
          href: "HandsOn_Exercises/HandsOn_Ex01/HandsOnEx01.html"
        - text: "Hands On Exercise 2"
          href: "HandsOn_Exercises/HandsOn_Ex02/HandsOnEx02.html"
        - text: "Hands On Exercise 3A"
          href: "HandsOn_Exercises/HandsOn_Ex03A/HandsOnEx03A.html"
        - text: "Hands On Exercise 3B"
          href: "HandsOn_Exercises/HandsOn_Ex03B/HandsOnEx03B.html"
        - text: "Hands On Exercise 4A"
          href: "HandsOn_Exercises/HandsOn_Ex04A/HandsOnEx04A.html" 
        - text: "Hands On Exercise 4B"
          href: "HandsOn_Exercises/HandsOn_Ex04B/HandsOnEx04B.html"  
        - text: "Hands On Exercise 4C"
          href: "HandsOn_Exercises/HandsOn_Ex04C/HandsOnEx04C.html"  
        - text: "Hands On Exercise 4D"
          href: "HandsOn_Exercises/HandsOn_Ex04D/HandsOnEx04D.html"
        - text: "Hands On Exercise 5"
          href: "HandsOn_Exercises/HandsOn_Ex05/HandsOnEx05.html"
        - text: "Hands On Exercise 6"
          href: "HandsOn_Exercises/HandsOn_Ex06/HandsOnEx06.html"
        
    - text: "In Class Exercises"
      menu:
        - text: "In Class Exercise 1"
          href: "InClass_Exercises/InClass_Ex01/InClassEx01.html"
        - text: "In Class Exercise 2"
          href: "InClass_Exercises/InClass_Ex02/InClassEx02.html"
        - text: "In Class Exercise 3 - MC 1"
          href: "InClass_Exercises/InClass_Ex03/MC1/InClassEx03.html"
    - text: "Take Home Exercises"
      menu:
        - text: "Take Home Exercise 1"
          href: "TakeHome_Exercises/TakeHome_Ex01/TakeHomeEx01.html"
        - text: "Take Home Exercise 2"
          href: "TakeHome_Exercises/TakeHome_Ex02/TakeHomeEx02.html"
        - text: "Take Home Exercise 3"
          href: "TakeHome_Exercises/TakeHome_Ex03/TakeHomeEx03.html"
          
    tools:
      - icon: github
        href: "https://github.com/sndrjcb/ISSS608-VAA"
      - icon: linkedin
        href: "https://www.linkedin.com/in/sandrajacob99/"
      - icon: telegram
        href: "https://t.me/sndrjcb"
  page-footer: 
    background: '#300713'
    border: false
    left: "Tracked by Google Analytics"
    right: "Copyright 2025, Sandra Jacob" 

format:
  html:
    theme: litera
    theme-options:
      font-family-base: "Nunito Sans"
    highlight-style: dracula
    title-block-banner: '#300713'
    title-block-banner-color: white
    fontcolor: black
    linkcolor: '#300713'
    footer-fg: "#ffffff"
    code-fold: true
    code-summary: "Code"
    code-tools: true
    code-overflow: scroll
    page-layout: full
    css: styles.css
    toc: true

editor: visual

execute:
  enabled: true
  engine: knitr

