project:
  type: website

website:
  title: "ISSS608-VAA"
  google-analytics: "G-8R61GXQYCW"
  navbar:
    left:
    - text: "Hands On Exercises"
      menu: 
        - text: "Hands On Exercise 1"
          href: "HandsOn_Exercises/HandsOn_Ex01/HandsOnEx01.html"
        - text: "Hands On Exercise 2"
          href: "HandsOn_Exercises/HandsOn_Ex02/HandsOnEx02.html"
        - text: "Hands On Exercise 3"
          href: "HandsOn_Exercises/HandsOn_Ex03/HandsOnEx03.html"
        - text: "Hands On Exercise 4"
          href: "HandsOn_Exercises/HandsOn_Ex04/HandsOnEx04.html"
          
    
    tools:
      - icon: github
        href: "https://github.com/sndrjcb/ISSS608-VAA"
      - icon: linkedin
        href: "https://www.linkedin.com/in/sandrajacob99/"
      - icon: telegram
        href: "https://t.me/sndrjcb"
  page-footer: 
    background: '#300713'
    border: false
    left: "Tracked by Google Analytics"
    right: "Copyright 2025, Sandra Jacob" 

format:
  html:
    theme: lux
    highlight-style: dracula
    title-block-banner: '#300713'
    title-block-banner-color: white
    fontcolor: black
    linkcolor: '#300713'
    footer-fg: "#ffffff"
    page-layout: full
    css: styles.css
    toc: true

editor: visual

