---
title: "Take Home Exercise 1"
subtitle: "Exploring Data Visualizations"
format: html
date: 05/01/2025
date-format: long
date-modified: last-modified
editor: visual
execute:
  eval: true
  echo: true
  warning: false
  freeze: true
---

# 1.1 Setting the Scene

Introduction & description of the dataset.

# **1.2 Our task**

In this exercise, Exploratory Data Analysis (EDA) methods and ggplot functions are used to explore:

-   the variations of age, sex, population between different planning areas and subzones

-   the distribution of Singapore overall population in terms of age, sex, etc.

# 1.3 Let's get started!

## **1.3.1 Loading packages**

We load the following R packages using the `pacman::p_load()` function:

-   **tidyverse**: Core collection of R packages designed for data science

-   **haven**: To read in data formats such as SAS and SPSS

-   **ggrepel**: to provides geoms for **ggplot2** to repel overlapping text labels

-   **ggthemes**: to use additional themes for **ggplot2**

-   **patchwork**: to prepare composite figure created using **ggplot2**

-   **ggridges**: to plot ridgeline plots

-   **ggdist**: for visualizations of distributions and uncertainty

-   **scales**: provides the internal scaling infrastructure used by **ggplot2**

## 1.3.2 Importing Data

Importing dataset

# 1.4 Data Pre-Processing

We first take a look at the data, and check if there are any duplicate entries using glimpse.

## 1.4.1 Glimpse

## **1.4.2 Checking data structure**

## 1.4.3 Checking for duplicate values

## 1.4.4 **Checking for missing values**

## **1.4.5 Filtering data for selected variables**

# 1.5 Exploratory Data Analysis (EDA)

# 1.? References


```{r}
library(leaflet)

lat <- 48
long <- 350

cat("title=", "World Map at", lat, long)

leaflet() |> addTiles() |> 
  setView(long, lat, zoom = 2)
```
